version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
